

services:
  flask:
    build:
      context: .
    container_name: flask_app
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    expose:
      - "5001"
    ports:
      - "5001:5001"  # Expose Flask app directly for testing (optional)
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s  # Allow some time for the Flask app to start

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      flask:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
