[project]
name = "improver"
version = "1.0.0"

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "py_config_gs/_version.py"
