name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on semantic versioning tags

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Get version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install setuptools wheel setuptools-scm

      - name: Build package
        run: |
          python -m build

      - name: Create Release
        id: create_release
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Creating release for tag $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Upload Package to Release
        if: startsWith(github.ref, 'refs/tags/v')  # Run this step if the tag starts with 'v'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
